baseURL: 'https://ehri.cz/'
languageCode: cs
title: Česká republika
theme: ehri-nn
copyright: '© 2010-{year} EHRI, český uzel EHRI.'
defaultContentLanguage: cs
dateFormat: '2 January 2006'
summaryLength: 40
params:
  titleShort: EHRI-CZ
  facebookUrl: 'https://www.facebook.com/profile.php?id=61565029209105'
  twitterUrl: 'https://x.com/Ehricz2024'
  blueskyUrl: 'https://bsky.app/profile/ehri-cz.bsky.social'
  contactName: EHRI CZ
  contactEmail: ehri@mua.cas.cz
  contactForm: false
  contactFormUrl: dummy
  env: production

# Menu configuration. Labels are in the i18n folders:
menu:
  main:
    - identifier: about
      pageRef: about
      weight: 20
    - identifier: partners
      pageRef: partners
      weight: 30
    - identifier: news
      pageRef: news
      weight: 40
    - identifier: services
      pageRef: services
      weight: 50
 #   - identifier: memogis
 #     parent: services
 #     pageRef: 'https://ehri.cz/memogis/praha/'
 #     weight: 10
 #   - identifier: holocaustcz
 #     parent: services
 #     pageRef: 'https://www.holocaust.cz/'
 #     weight: 20
 #   - identifier: terezin_research_guide
 #     parent: services
 #     pageRef: 'https://portal.ehri-project.eu/guides/terezin'
 #     weight: 30
 #  - identifier: geodata
 #     parent: services
 #     pageRef: 'https://geodata.ehri-project.eu/'
 #     weight: 40
    - identifier: contact
      pageRef: contact
      weight: 60
  footer:
    - identifier: about
      pageRef: about
      weight: 20
    - identifier: partners
      pageRef: partners
      weight: 30
    - identifier: news
      pageRef: news
      weight: 40
  services:
    - identifier: memogis
      pageRef: 'https://ehri.cz/memogis/praha/'
      weight: 10
    - identifier: holocaustcz
      pageRef: 'https://www.holocaust.cz/'
      weight: 20
    - identifier: terezin_research_guide
      pageRef: 'https://portal.ehri-project.eu/guides/terezin'
      weight: 30
    - identifier: geodata
      pageRef: 'https://geodata.ehri-project.eu/'
      weight: 40


# Language overrides for menu config. TODO: figure out
# how not to duplicate things in e.g. the services menu
languages:
  cs:
    title: Česká republika
    weight: 1
    menu:
      main:
        - identifier: about
          pageRef: about
          weight: 20
        - identifier: partners
          pageRef: partners
          weight: 30
        - identifier: news
          pageRef: news
          weight: 40
        - identifier: newsletters
          pageRef: newsletters
          weight: 45
        - identifier: services
          pageRef: services
          weight: 50
#        - identifier: memogis
#          parent: services
#          pageRef: 'https://ehri.cz/memogis/praha/'
#          weight: 10
#        - identifier: holocaustcz
#          parent: services
#          pageRef: 'https://www.holocaust.cz/'
#          weight: 20
#        - identifier: terezin_research_guide
#          parent: services
#          pageRef: 'https://portal.ehri-project.eu/guides/terezin'
#          weight: 30
#        - identifier: geodata
#          parent: services
#          pageRef: 'https://geodata.ehri-project.eu/'
#          weight: 40
        - identifier: contact
          pageRef: contact
          weight: 60
      footer:
        - identifier: about
          pageRef: about
          weight: 20
        - identifier: partners
          pageRef: partners
          weight: 30
        - identifier: news
          pageRef: news
          weight: 40
      services:
        - identifier: memogis
          pageRef: 'https://ehri.cz/memogis/praha/'
          weight: 10
        - identifier: holocaustcz
          pageRef: 'https://www.holocaust.cz/'
          weight: 20
        - identifier: terezin_research_guide
          pageRef: 'https://portal.ehri-project.eu/guides/terezin'
          weight: 30
        - identifier: geodata
          pageRef: 'https://geodata.ehri-project.eu/'
          weight: 40

  en:
    title: Czech Republic
    weight: 2
  
markup:
  goldmark:
    renderer:
      unsafe: true
